image: archlinux
packages:
  - nodejs
  - npm
secrets:
  - bad5de78-80a3-41b1-8f40-21a1d0ae63a6
environment:
  # Replace this ID with your site's API ID
  NETLIFY_SITE_ID: 35283bf6-b739-4d7c-b146-dd5c0077bf50
tasks:
  - deploy: |
      cd kily/public
      {
        set +x
        . ~/.buildsecrets
        set -x
      }
      export NETLIFY_AUTH_TOKEN
      npm run deploy
